apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        jobLabel: node-exporter
    spec:
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: ''
      - name: sys
        hostPath:
          path: /sys
          type: ''
      - name: root
        hostPath:
          path: /
          type: ''
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:v1.4.0
        args:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--path.rootfs=/host/root'
        - '--web.listen-address=[$(HOST_IP)]:9100'
        - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)'
        - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
        ports:
        - name: http-metrics
          hostPort: 9100
          containerPort: 9100
          protocol: TCP
        env:
        - name: HOST_IP
          value: 0.0.0.0
        resources: {}
        volumeMounts:
        - name: proc
          readOnly: true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        - name: root
          readOnly: true
          mountPath: /host/root
          mountPropagation: HostToContainer
        livenessProbe:
          httpGet:
            path: /
            port: 9100
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9100
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter-service
    jobLabel: node-exporter
spec:
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
  - port: 9100
    name: http-metrics

