apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  labels:
    app: vmalert
  name: vmalert-service
spec:
  ports:
    - name: http
      port: 8880
      targetPort: http
      protocol: TCP
  selector:
    app: vmalert
  type: "ClusterIP"