secretGenerator:
  - name: mysql-secret
    literals:
      - username=mysqluser
      - password=password
      - db_name=db
namespace: wordpress
resources:
  - mysql-st.yaml
  - wordpress-dep.yaml
  - ingress.yaml