---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
  namespace: monitoring
spec:
  rules:
    - host: "mon.home.local"
      http:
        paths:
          - pathType: Prefix
            path: /vm
            backend:
              service:
                name: vmsingle-vmsingle-pvc
                port:
                  number: 8429
      