apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: pod-scrape
  namespace: monitoring
spec:
  discoveryRole: "endpoints"
  jobLabel: "app.kubernetes.io/name"
  endpoints:
    - port: metrics
  namespaceSelector:
    any: true
  selector: {}