---
# Source: victoria-metrics-alert/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-victoria-metrics-alert
  namespace: default
  labels:
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
---
# Source: victoria-metrics-alert/templates/server-alerts-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-victoria-metrics-alert-server-alert-rules-config
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
data:
  alert-rules.yaml: |
    
    groups:
    - name: alertmanager.rules
      rules:
      - alert: AlertmanagerFailedReload
        annotations:
          description: Configuration has failed to load for {{ $labels.namespace }}/{{$labels.pod}}.
          runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagerfailedreload
          summary: Reloading an Alertmanager configuration has failed.
        expr: max_over_time(alertmanager_config_last_reload_successful{job="vmalertmanager-vm",namespace="monitoring"}[5m])
          == 0
        for: 10m
        labels:
          severity: critical
---
# Source: victoria-metrics-alert/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-victoria-metrics-alert-server-clusterrolebinding
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: release-name-victoria-metrics-alert
    namespace: default
roleRef:
  kind: ClusterRole
  name: release-name-victoria-metrics-alert-server-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: victoria-metrics-alert/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  release-name-victoria-metrics-alert-server
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
rules: []
---
# Source: victoria-metrics-alert/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-victoria-metrics-alert-server
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-victoria-metrics-alert-server
subjects:
- kind: ServiceAccount
  name: release-name-victoria-metrics-alert
  namespace: default
---
# Source: victoria-metrics-alert/templates/server-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
  name: release-name-victoria-metrics-alert-server
spec:
  ports:
    - name: http
      port: 8880
      targetPort: http
      protocol: TCP
  selector:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
  type: "ClusterIP"
---
# Source: victoria-metrics-alert/templates/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-victoria-metrics-alert-server
  namespace: default
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app: server
      app.kubernetes.io/name: victoria-metrics-alert
      app.kubernetes.io/instance: release-name
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        app.kubernetes.io/name: victoria-metrics-alert
        app.kubernetes.io/instance: release-name
        helm.sh/chart: victoria-metrics-alert-0.7.2
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/config: fc8e8f5b4d022866103962223be52aa5d4e220c9dc128c5b4d71e848e12a7759
    spec:
      serviceAccountName: release-name-victoria-metrics-alert
      securityContext:
        {}
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-alert-server
          securityContext:
            {}
          image: "victoriametrics/vmalert:v1.92.1"
          args:
            - -rule=/config/alert-rules.yaml
            - -datasource.url=http://vmsingle-vmsingle.monitoring.svc:8429/vm
            - -notifier.url=http://alertmanager-service.monitoring.svc:9093
            - -remoteRead.url=
            - -remoteWrite.url=
            - -envflag.enable=true
            - -envflag.prefix=VM_
            - -http.pathPrefix=/vmalert
            - -loggerFormat=json
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8880
          readinessProbe:
            httpGet:
              path: /vmalert/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: alerts-config
              mountPath: /config
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - image: reloader-image
          name: config-reloader
      volumes:
        - name: alerts-config
          configMap:
            name: release-name-victoria-metrics-alert-server-alert-rules-config
---
# Source: victoria-metrics-alert/templates/server-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: server
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/instance: release-name
    helm.sh/chart: victoria-metrics-alert-0.7.2
    app.kubernetes.io/managed-by: Helm
  
  name: release-name-victoria-metrics-alert-server
  namespace: default
spec:
  rules:
  - host: mon.home.local
    http:
      paths:
        - path: /vmalert
          pathType: Prefix
          backend:
            service:
              name: release-name-victoria-metrics-alert-server
              port:
                number: 8880
