fullnameOverride: keycloak
nameOverride: keycloak
replicas: 1

serviceAccount:
  create: false
rbac:
  create: false

# args: 
#   - -Dkeycloak.profile.feature.docker=enabled

extraEnv: |
  - name: KC_CACHE
    value: ispn
  - name: KEYCLOAK_LOGLEVEL
    value: INFO
  - name: KC_CACHE_STACK
    value: kubernetes
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: password
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: dns.DNS_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: 'dns_query=keycloak-headless'

service:
  httpPort: 8080
  httpsPort: 8443

ingress: 
  enabled: true
  # annotations:
  #   cert-manager.io/cluster-issuer: ca-issuer
  rules:
    - host: keycloak.dev.local
      paths:
        - path: /auth/admin
          pathType: Prefix
  # tls: 
  #   - hosts:
  #     - keycloak.dev.local
  #     secretName: keycloak-tls

postgresql:
  enabled: true
  postgresqlUsername: keycloak
  postgresqlPassword: keycloak

  
