replicaCount: 1
nameOverride: keycloak
fullnameOverride: keycloak

auth:
  adminUser: admin
  adminPassword: password


extraEnvVars:
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KEYCLOAK_ENABLE_HTTPS
    value: "false"
  - name: KEYCLOAK_PROXY
    value: edge
  - name: KEYCLOAK_PRODUCTION
    value: "true"
  - name: PORT
    value: "8080"
  

ingress:
  enabled: false
  

postgresql:
  enabled: true
