apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
      #   - name: www
      #     persistentVolumeClaim:
      #       claimName: pvc-nfs-www
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs-data
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        #   - mountPath: /usr/share/nginx/html
        #     name: www
          - mountPath: /var/log/nginx
            name: data
  
