# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-nfs-data
# spec:
#   storageClassName: nfs-client
#   resources:
#     requests:
#       storage: 2Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      # volumes:
      #   - name: www
      #     persistentVolumeClaim:
      #       claimName: pvc-nfs-data
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
          name: web
        resources: 
          limits:
            cpu: 50m
            memory: 50Mi
          requests: 
            cpu: 10m
            memory: 10Mi
        # volumeMounts:
        #   - mountPath: /usr/share/nginx/html
        #     name: www
---       
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  selector:
    app: nginx-app
  ports:
  - port: 80
    name: web

  
