apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
             - matchExpressions:
                 - key: color
                   operator: In
                   values:
                     - red
      volumes:
        - name: www
          hostPath:
            path: /var/www
            type: DirectoryOrCreate
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
          name: web
        resources: {}
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: www
         
  
