apiVersion: v1
kind: LimitRange
metadata:
  name: limit1
  namespace: ns1
  labels:
    limits: limit1
spec:
  limits:
    - type: Container
      min:
        memory: 10Mi
      default:
        cpu: 100m
        memory: 75Mi
      defaultRequest:
        cpu: 50m
        memory: 32Mi
        
