apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    service: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - port: 83
    nodePort: 30010
    targetPort: web
  