---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    deplo: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:

      volumes:
        - name: nginx-log
          emptyDir: {}
            
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /var/log/nginx
            name: nginx-log

      - name: logger
        image: busybox
        command: 
          - "/bin/sh"
        args:
          - "-c"
          - "while true; do cat /var/log/nginx/access.log; sleep 30; done"
        volumeMounts:
          - mountPath: /var/log/nginx
            name: nginx-log
