apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx-pod-ssd
  name: nginx-pod-ssd
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  restartPolicy: Always
  nodeSelector:
    disktype: ssd
status: {}
