apiVersion: v1
kind: Secret
metadata:
  name: mysupersecret
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmRoZWxsbw==
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-secretvolume
  namespace: default

spec:
  volumes: 
    - name: secret-volume
      secret:
        secretName: mysupersecret
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secre-folder
        readOnly: true
   