apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-ns1
  namespace: ns1
  labels:
    quota: quota-ns1
spec:
  hard:
    limits.cpu: '1'
    limits.memory: 750Mi
    persistentvolumeclaims: '2'
    pods: '10'
    requests.cpu: 500m
    requests.memory: 320Mi
    services: '10'
    
