---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: nginx-set
  serviceName: nginx-set
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-set
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www-pvc
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-statefull
spec:
  clusterIP: None
  selector:
    app: nginx-set
  ports:
  - port: 80
    targetPort: web
   
  

