apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: 
    
    run: staticpod
  name: static_nginx
spec:
  containers:
  - image: nginx
    name: staticpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
