apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx-service"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: web-data
          configMap:
            name: html
      initContainers:
        - name: init
          image: busybox:latest
          volumeMounts:
            - mountPath: /tmp-html
              name: web-data
            - mountPath: /html
              name: www
          command:
            - "sh"
            - "-c"
            - "cp /tmp-html/index.html /html/index.html"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  clusterIP: None
  ports:
  - name: web
    protocol: TCP
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-sts-o
  namespace: default
spec:
  selector:
    app: nginx
    statefulset.kubernetes.io/pod-name: nginx-sts-0
  ports:
  - name: web
    protocol: TCP
    port: 80
    
   