apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat

spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat
        image: tomcat
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: tomcat
          containerPort: 80
          protocol: TCP
          
