apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      labels:
        app: busybox1
    spec:
      volumes:
        - name: shared-volume
          emptyDir:
            sizeLimit: 500Mi
      containers:
      - name: myapp1
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "sleep"
          - "300"
        volumeMounts:
          - mountPath: /busybox1
            name: shared-volume
      - name: myapp2
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "sleep"
          - "300"
        volumeMounts:
          - mountPath: /busybox2
            name: shared-volume
  
          
       

   
    
    
