apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceAccountName: vmagent
  selectAllByDefault: true
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  extraArgs:
    memory.allowedPercent: "40"
    loggerFormat: json
  remoteWrite:
  - url: "http://vmsingle-vmsingle.monitoring.svc:8429/vm/api/v1/write"
