apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vm
  namespace: monitoring
spec:
  image:
    tag: v1.93.3
  serviceAccountName: vmagent
  selectAllByDefault: true
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  scrapeInterval: 60s
  logFormat: json
  replicaCount: 2
  vmAgentExternalLabelName: vmagentha
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  extraArgs:
    memory.allowedPercent: "40"
    loggerFormat: json
    http.pathPrefix: /vmagent
    promscrape.streamParse: "true"
  remoteWrite:
  - url: "http://vmsingle-vm.monitoring.svc:8429/vm/api/v1/write"
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        resources:
            requests:
              storage: 2Gi
