apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  image:
    tag: v1.91.3
  serviceAccountName: vmagent
  selectAllByDefault: true
  scrapeInterval: 25s
  logFormat: json
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  extraArgs:
    memory.allowedPercent: "40"
    loggerFormat: json
    http.pathPrefix: /vmagent
    promscrape.streamParse: "true"
  remoteWrite:
  - url: "http://vmsingle-vmsingle.monitoring.svc:8429/vm/api/v1/write"
