apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceAccountName: vmagent
  selectAllByDefault: true
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 600Mi
  extraArgs:
    memory.allowedPercent: "40"
    loggerFormat: json
    http.pathPrefix: /vmagent
  remoteWrite:
  - url: "http://vmsingle-vmsingle.monitoring.svc:8429/vm/api/v1/write"
