apiVersion: v1
kind: ConfigMap
metadata:
  name: old-index-cm
data:
  index.html: |
    old-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: old-nginx
  name: old-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: old-nginx
  template:
    metadata:
      labels:
        app: old-nginx
    spec:
      containers:
      - image: nginx:1.13
        name: nginx
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources: {}
        ports:
          - name: old-nginx-port
            containerPort: 80
        volumeMounts:
          - name: index
            mountPath: /usr/share/nginx/html
      volumes:
        - name: index
          configMap:
            name: old-index-cm

---
apiVersion: v1
kind: Service
metadata:
  name: old-nginx-svc
spec:
  selector:
    app: old-nginx
  ports:
  - port: 8080
    targetPort: old-nginx-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: old-nginx-ing
  labels:
    name: old-nginx-ing
spec:
  rules:
  - host: old-nginx.home.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: old-nginx-svc
            port: 
              number: 8080


          
          
