apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vm-operator
  name: vm-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vm-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vm-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        - --zap-log-level=info
        command:
        - manager
        env:
        - name: WATCH_NAMESPACE
          value: ""
        image: victoriametrics/operator:v0.35.1
        name: manager
        resources:
          limits:
            cpu: 120m
            memory: 520Mi
          requests:
            cpu: 80m
            memory: 120Mi
        ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9443
              name: webhook
              protocol: TCP
      serviceAccountName: vm-operator
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name:  vm-operator-service
  labels:
    app.kubernetes.io/name: vm-operator-service
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: vm-operator
  ports:
  - name:  http
    port:  8080
    targetPort:  http