
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sys-utils
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/vladoz77/k8s.git
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
  