apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  extraArgs:
    http.pathPrefix: /vm
  retentionPeriod: "1"
  logFormat: json
  removePvcAfterDelete: true
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 2Gi
  storage:
    storageClassName: nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
