apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle-pvc
  namespace: monitoring
spec:
  extraArgs:
  # http.pathPrefix: /vm
  retentionPeriod: "1"
  removePvcAfterDelete: true
  storage:
<<<<<<< HEAD
    storageClassName: standard
=======
    storageClassName: nfs
>>>>>>> 11e7fc6900e944903a672571653fccecf4af2a62
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
