apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  extraArgs:
    http.pathPrefix: /vm
  retentionPeriod: "1"
  removePvcAfterDelete: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 250Mi
  storage:
    storageClassName: nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
