apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  image:
    tag: v1.91.3
  extraArgs:
    http.pathPrefix: /vm
    vmalert.proxyURL: http://vmalert-vmalert.monitoring.svc:8080
  retentionPeriod: "14"
  logFormat: json
  removePvcAfterDelete: true
  storage:
    storageClassName: nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  resources:
    limits:
      cpu: 1200m
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
