# API server
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: apiserver
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      # tier: kubernetes
---

#Cadvisor
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  interval: 30s
  path: /metrics/cadvisor
  scheme: https
  scrapeTimeout: 5s
  relabelConfigs:
    - targetLabel: job
      replacement: cadvisor
    - source_labels: [__meta_kubernetes_node_name]
      target_label: node
  # metricRelabelConfigs:
  #       - action: drop
  #         regex:  container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
  #         sourceLabels:
  #           - __name__
  #       - action: drop
  #         regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
  #         sourceLabels:
  #           - __name__
  #       - action: drop
  #         regex: container_memory_(mapped_file|swap)
  #         sourceLabels:
  #           - __name__
  #       - action: drop
  #         regex: container_(file_descriptors|tasks_state|threads_max)
  #         sourceLabels:
  #           - __name__
  #       - action: drop
  #         regex: container_spec.*
  #         sourceLabels:
  #           - __name__
  #       - action: drop
  #         regex: .+;
  #         sourceLabels:
  #           - id
  #           - pod
  
---

# kube-controller
apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-controller-manager-metrics
    jobLabel: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  ports:
  - port: 10257
    targetPort: 10257
    name: metrics

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-controller-manager
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-controller-manager-metrics
---

#Kube-dns
apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metric-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-dns-service
    jobLabel: kube-dns
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9153
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  clusterIP: None
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-dns
  namespace: monitoring
  labels:
    app: kube-dns
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
       app.kubernetes.io/name: kube-dns-service
---

#kube-proxy
apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-metrics-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-proxy-metrics-service
    jobLabel: kube-proxy
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 10249
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  clusterIP: None

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-proxy
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-proxy-metrics-service
---

#kube-scheduller
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-scheduler-metrics
    jobLabel: kube-scheduler
spec:
  selector:
    component: kube-scheduler
  ports:
  - port: 10259
    targetPort: 10259
    name: metrics

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-scheduler
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecureSkipVerify: true
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-scheduler-metrics
---

#Kubelet
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
  namespace: monitoring
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  honorLabels: true
  interval: 30s
  scheme: https
  scrapeTimeout: 5s
  relabelConfigs:
        - replacement: kubelet
          targetLabel: job