apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-dep
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
        - name: www
          configMap:
             name: index-html
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html

            

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <html>
    <head>
        <title>Тестовая страница</title>
        <meta charset="UTF-8">
    </head>
    <body>
    <h1>Тестовая страница</h1>
    <p>Простая тестовая страница, версия 10</a>.
    </p>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
  - port: 80
    targetPort: 80



