apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mail-service-endpoint
  labels:
    kubernetes.io/service-name: mail-service
addressType: IPv4
ports:
- name: ""
  port: 80
endpoints:
- addresses:
  - "217.69.139.200"
  - "217.69.139.202"
  - "94.100.180.200"
  - "94.100.180.201"

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  ports:
  - port: 8080
    targetPort: 80
