apiVersion: v1
kind: Endpoints
metadata:
  name: node-export-service
subsets:
- addresses:
  - ip: 192.168.49.1
  ports:
  - port: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: node-export-service
spec:
  ports:
  - port: 9100

