apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprod-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: preprod
  hostPath:
    path: /preprod