apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prod
  hostPath:
    path: /prod