apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-pvc
  namespace: prod
spec:
  storageClassName: prod
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
