authentik:
    secret_key: "secretkey"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "postgres"
    email:
      host: smtp.gmail.com
      port: 465
      username: vladozz23@gmail.com
      password: irjckbsajihmbpjq
      use_tls: false
      use_ssl: true
      timeout: 30
      from: authentik@gmail.com

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: nginx 
        enabled: true
        hosts:
            - oauth.home.local

postgresql:
    enabled: true
    auth:
        password: "postgres"
    primary:
        extendedConfiguration: |
            max_connections = 500
        persistence:
          enabled: true
          storageClass: standard
          accessModes:
            - ReadWriteOnce
redis:
    enabled: true