apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-www
spec:
  storageClassName: nfs-www
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce