apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-ingress
  namespace: monitoring
spec:
  rules:
  - host: "mon.home.local"
    http:
      paths:
      - pathType: Prefix
        path: /alertmanager
        backend:
          service:
            name: alertmanager-service-headless
            port:
              number: 9093