apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-issure
  namespace: argocd
spec:
  ca:
    secretName: kube-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  duration: 9125h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
    - k8s
  secretName: argocd-cert-secret
  issuerRef:
    name: argocd-issure
    kind: Issuer
  commonName: "argocd.local"
  dnsNames:
  - "argocd.local"