apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-metrics-service
  namespace: kube-system
  labels:
    app: kube-proxy-metrics-service
    jobLabel: kube-proxy
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 10249
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  clusterIP: None

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-proxy
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-proxy-metrics-service
