apiVersion: v1
kind: Service
metadata:
  name: kube-dns-metric-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-dns-service
    jobLabel: kube-dns
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9153
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  clusterIP: None
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-dns
  namespace: monitoring
  labels:
    app: kube-dns
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
       app.kubernetes.io/name: kube-dns-service