apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: ingress-nginx-metrics
  labels:
    app.kubernetes.io/name: ingress-nginx-metrics
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - port: 10254
    name: metrics

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-metrics
  namespaceSelector:
    matchNames:
    - ingress-nginx
