apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: grafana-metrics
  name: grafana-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: http-grafana
    path: grafana/metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-service
  namespaceSelector:
    matchNames:
    - monitoring