apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini-cfg
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = mon.home.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true
