apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasourse-cfg
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "victoria-metrics",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://vmsingle-vmsingle.monitoring.svc.cluster.local:8429/vm",
                "version": 1
            }
        ]
    }
