apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cfg
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = mon.home.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true

  datasources.yaml: |
    apiVersion: 1
    datasources:
     - access: proxy
       isDefault: true
       name: victoria
       type: prometheus
       url: http://vmsingle-vmsingle.monitoring.svc.cluster.local:8429/vm

  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
      - disableDeletion: true
        editable: true
        folder: ""
        name: default
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
        updateIntervalSeconds: 30
