apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cfg
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = mon.home.local
    root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
    serve_from_sub_path = true

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      name: victoria-metrics
      orgId: 1
      type: prometheus
      url: http://vmsingle-vm.monitoring.svc.cluster.local:8429/vm
      version: 1

    - access: proxy
      editable: true
      name: loki
      orgId: 1
      type: loki
      url: http://loki-gateway.loki.svc
      version: 1

  dashboards.yaml: |-
    apiVersion: 1
    providers: 
      - name: victoria-metrics
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
        type: file
