apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-client-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sys-utils
  source:
    repoURL: 'https://github.com/vladoz77/k8s.git'
    path: argocd/sys_utils_project/nfs-provisioner
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-provisioner