apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  serviceAccountName: assa
  containers:
  - image: alpine
    name: mypod
    args: ["sleep", "3600"]
   
    
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
