apiVersion: v1
kind: ServiceAccount
metadata:
  name: assa
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assa-role
rules: 
  - apiGroups: 
     - "*"
    resources: 
     - pods
    verbs: 
     - list
     - get
     - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assa-rolebinding
  namespace: default
roleRef: 
  kind: Role
  name: assa-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: assa
    namespace: default

