apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmsingle-app
  namespace: monitoring
spec:
  project: sys-utils
  source:
    repoURL: 'https://github.com/vladoz77/k8s.git'
    path: argocd/sys_utils_project/monitoring/vmsingle
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
