apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmagent-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: sys-utils
  source:
    repoURL: 'https://github.com/vladoz77/k8s.git'
    path: argocd/sys_utils_project/monitoring/vmagent
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
