apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: argocd-metrics
  name: argocd-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-repo-server
          - argocd-applicationset-controller
  namespaceSelector:
    matchNames:
      - argocd

# ---
# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMServiceScrape
# metadata:
#   labels:
#     app.kubernetes.io/name: argocd-server-metrics
#   name: argocd-server-metrics
#   namespace: monitoring
# spec:
#   endpoints:
#   - port: metrics
#     interval: 30s
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: argocd-server-metrics
#   namespaceSelector:
#     matchNames:
#     - argocd

# ---
# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMServiceScrape
# metadata:
#   labels:
#     app.kubernetes.io/name: argocd-repo-server
#   name: argocd-repo-server
#   namespace: monitoring
# spec:
#   endpoints:
#   - port: metrics
#     interval: 30s
#     path: /metrics
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: argocd-repo-server
#   namespaceSelector:
#     matchNames:
#     - argocd
    