apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmalert-ingress
  namespace: monitoring
spec:
  rules:
  - host: "mon.home.local"
    http:
      paths:
      - pathType: Prefix
        path: /vmalert
        backend:
          service:
            name: vmalert-vmalert
            port:
              number: 8080