apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  interval: 30s
  path: /metrics/cadvisor
  scheme: https
  scrapeTimeout: 5s
  metricRelabelConfigs:
        - action: drop
          regex: >-
            container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
          sourceLabels:
            - __name__
        - action: drop
          regex: >-
            container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_memory_(mapped_file|swap)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_(file_descriptors|tasks_state|threads_max)
          sourceLabels:
            - __name__
        - action: drop
          regex: container_spec.*
          sourceLabels:
            - __name__
        - action: drop
          regex: .+;
          sourceLabels:
            - id
            - pod
  relabelConfigs:
        - replacement: cadvisor
          targetLabel: job
  