apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  labels:
    app.kubernetes.io/name: kube-probes
  name: kube-probes
  namespace: monitoring
spec:
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  honorLabels: true
  interval: 30s
  path: /metrics/probes
  scheme: https
  scrapeTimeout: 5s
  tlsConfig:
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecureSkipVerify: true
  
