apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metallb-controller
  name: metallb-controller-metrics
  namespace: metallb-system
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 7472
  selector:
    app: metallb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metallb-speaker
  name: metallb-speaker-metrics
  namespace: metallb-system
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 7472
  selector:
    app: metallb

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: metallb
  namespace: monitoring
spec:
  endpoints:
  - port: metrics-port
  selector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - metallb-speaker
      - metallb-controller
  namespaceSelector:
    matchNames:
    - metallb-system