apiVersion: v1
kind: Service
metadata:
  name: node-local-dns-metrics-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: node-local-dns-metrics-service
    jobLabel: node-local-dns
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9253
      targetPort: 9253
  selector:
     k8s-app: node-local-dns
  clusterIP: None
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-local-dns
  namespace: monitoring
  labels:
    app: node-local-dns
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: node-local-dns-metrics-service