apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vm-victoria-metrics-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: vm-operator-service
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - monitoring