apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vm-victoria-metrics-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
        control-plane: vm-operator
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - monitoring