apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma-dep
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
      - name: karma
        image: ghcr.io/prymitive/karma:latest
        env:
        - name: CONFIG_FILE
          value: /etc/karma/karma.conf
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
          name: http-karma
        volumeMounts:
        - name: karma-vm
          mountPath: /etc/karma/

      volumes:
      - name: karma-vm
        configMap:
          name: karma-cm

---
apiVersion: v1
kind: Service
metadata:
  name: karma-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: karma-service
spec:
  selector:
    app: karma
  ports:
  - port: 8080
    name: http-karma

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karma-ingress
  namespace: monitoring
spec:
  rules:
  - host: "karma.home.local"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: karma-service
            port:
              number: 8080
