apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: karma-metrics
  name: karma-metrics
  namespace: monitoring
spec:
  endpoints:
  - port: http-karma
    interval: 30s
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: karma-service
  namespaceSelector:
    matchNames:
    - monitoring
