apiVersion: v1
kind: Service
metadata:
  labels:
    app: old-nginx
    type: canary
  name: old-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: canary
status:
  loadBalancer: {}
