apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: old-nginx
    type: canary # add label type=canary
  name: old-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: old-nginx
      type: canary
  template:
    metadata:
      labels:
        app: old-nginx
        type: canary # add label type=canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
