apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: testcontainer
    image: nginx
    # lifecycle hook spec
    lifecycle:
      postStart:
      # Your Exec handler
        exec:
          command: ["/bin/sh", "-c",  "echo postStart hook executed > /test.log"]
