apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-dep
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-app
  template:
    metadata:
      labels:
        app: pgadmin-app
    spec:
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: data
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        env:
         - name: PGADMIN_DEFAULT_EMAIL
           value: user@domain.com
         - name: PGADMIN_DEFAULT_PASSWORD
           value: password
         - name: PGADMIN_PORT
           value: "80"
         - name:  PGADMIN_CONFIG_SERVER_MODE
           value: "False"
        ports:
        - containerPort: 80
          name: pgadmin-port
        volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: database
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-dep
  namespace: database
spec:
  ports:
  - port: 80
    protocol: TCP
    name: pgadmin-port
  selector:
    app: pgadmin-app
  type: LoadBalancer