apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: database
data:
#env
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "secret"
  POSTGRES_DB: "database"
  PGDATA : /var/lib/postgresql/data/pgdata


