apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: database
spec:
  clusterIP: None
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc-con
  namespace: database
spec:
  type: LoadBalancer
  selector:
    app: postgresql-app
    statefulset.kubernetes.io/pod-name: postgresql-sts-0
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "secret"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  namespace: database
data:
  POSTGRES_DB: "database"
  PGDATA : /var/lib/postgresql/data/pgdata

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-sts
  namespace: database
spec:
  selector:
    matchLabels:
      app: postgresql-app
  serviceName: postgresql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-app
    spec:
      volumes:
        - name: postgresql-conf-volume
          configMap:
            name: postgresql-conf-file
      containers:
      - name: postgresql
        image: postgres:14
        args: ["-c", "config_file=/etc/postgresql.conf"]
        envFrom:
          - configMapRef:
              name: pg-config
          - secretRef:
              name: pg-secret
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
        - name: postgresql-conf-volume
          mountPath: /etc/postgresql.conf
          subPath: postgresql.conf
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 10Gi
