apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: database
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer-ca
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer-database
  namespace: database
spec:
  ca:
    secretName: root-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-crt
  namespace: database
spec:
  secretName: pgadmin-crt-crt
  issuerRef:
    name: my-ca-issuer-database
    kind: Issuer
  commonName: pgadmin-crt
  dnsNames:
  - "pgadmin.local"