apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: default-selfsigned
    namespace: cert-manager
spec:
    selfSigned: {}

